service: serverless-dojo

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

  stage: dev
  region: us-east-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:GetRecords
        - dynamodb:GetShardIterator
        - dynamodb:DescribeStream
        - dynamodb:ListStreams
        - sqs:SendMessage
      Resource: '*'

functions:
  createUser :
    handler: src/api/createUser.handler
    environment:
      DYNAMODB_USERS: 'Users'
    events:
     - http:
         path: users
         method: post

  prepareEmail :
    handler: src/stream/prepareEmail.handler
    environment:
      QUEUE_URL: 
        Ref: SendEmail
    events:
     - stream:
          type: dynamodb
          arn:
            Fn::GetAtt: 
              - UsersTable
              - StreamArn
     
  sendEmail :
    handler: src/consumer/sendEmail.handler
    reservedConcurrency: 10
    events:
     - sqs:
          arn:
            Fn::GetAtt:
              - SendEmail
              - Arn

resources:
  Resources:
    UsersTable:
          Type: AWS::DynamoDB::Table
          Properties:
            TableName: Users
            AttributeDefinitions:
              - AttributeName: id
                AttributeType: S
            KeySchema:
              - AttributeName: id
                KeyType: HASH
            ProvisionedThroughput:
              ReadCapacityUnits: 1
              WriteCapacityUnits: 1
            StreamSpecification:
              StreamViewType: NEW_IMAGE
    SendEmail:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "SendEmail"
        RedrivePolicy:
          deadLetterTargetArn:
            Fn::GetAtt:
              - SendEmailDLQ
              - Arn
          maxReceiveCount: 3
    SendEmailDLQ:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "SendEmailDLQ"
